version: "3.8"

networks:
  common-network:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - common-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: toplaiphaiwin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - common-network

volumes:
  postgres_data:
  pgadmin_data:
