version: "3.8"

networks:
  common-network:
    external: true

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    # set password
    command: ["redis-server", "--requirepass", "123456"]
    volumes:
      - redis-data:/data
    networks:
      - common-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - common-network

volumes:
  redis-data:
